### ISSUE TITLE
which version support usbcontext?  Answer: V3 (main git branch)

### ISSUE THREAD

**Issue by lxa520** [LibUsbDotNet/LibUsbDotNet#111]
1. which version support usbcontext
2. How to know the version of libusbdotnet corresponding to the submitted version

**Comment by qzzf1w** [comment]
I am running samples with latest code and usbcontext isnt there?

**Comment by shawty** [comment]
Snap, same here....

**Comment by shawty** [comment]
Update:

I have gone back through every version offered on NUGet:

![image](https://user-images.githubusercontent.com/1876454/104309289-d134f300-54c9-11eb-922e-5a023eb4b1cf.png)

And "UsbContext()" is not found in any of them.

**Comment by shawty** [comment]
Update 2:

After examining the object browser in VS, I find this (For the most recent version)

![image](https://user-images.githubusercontent.com/1876454/104310749-1c500580-54cc-11eb-9450-3a3dcd302eb6.png)

When looking in the same examples folder as the previously mentioned C# example, there is also a Visual Basic sample (https://github.com/LibUsbDotNet/LibUsbDotNet/blob/master/src/Examples/Read.Write/ReadWrite.vb)

Upon examining the code in the visual basic sample, it appears to NOT USE the UsbContext as the C# sample does, but instead uses the "UsbDeviceFinder" as seen in the object explorer screen shot.

Translating the bulk of the VB code to C# gives us the following:

![image](https://user-images.githubusercontent.com/1876454/104310955-78b32500-54cc-11eb-857b-b2afbda5af44.png)

And that code compiles and works with the current NuGet version.

It appears the solution to this issue is to bring the examples for C# up to the same version the VB samples clearly target.

**Comment by qzzf1w** [comment]
Ch-Ching!

**Comment by shawty** [comment]
So has this been closed without updating the C# example in the repo then?

By doing that, you'll only have future developers who are not aware of this, opening new issues saying that "UsbContext" is not found.

**Comment by mcuee** [comment]
Hmm, examples have been updated.
https://github.com/LibUsbDotNet/LibUsbDotNet/blob/v2/stage/Examples/Read.Write/ReadWrite.cs

**Comment by shawty** [comment]
You missed one:

https://github.com/LibUsbDotNet/LibUsbDotNet/blob/master/src/Examples/Read.Write/ReadWrite.cs

This was the actual C# example I cited in "Post Number 3" above ^^^^^

😊

**Comment by mcuee** [comment]
Okay, I will reopen this one as Example.

**Comment by shawty** [comment]
No worries, just wanted to make sure you where not causing yourself any extra work with other devs reading this, seeing it closed and asking for help.

**Comment by mcuee** [comment]
@shawty If you use mainline git or the nuget 3.x-alpha version, UsbContext() is there. If you use V2 branch, the examples has no UsbContext().
https://github.com/LibUsbDotNet/LibUsbDotNet/issues/89

**Comment by shawty** [comment]
Yup, go for it.
