### ISSUE TITLE
LibUsbDotNet NuGet package

### ISSUE THREAD

**Issue by andrasfuchs** [LibUsbDotNet/LibUsbDotNet#6]
Since this repo is the successor of LibUsbDotNet appointed by Travis, I think you should discuss with GeorgeHahn, the owner of the current LibUsbDotNet NuGet package (https://www.nuget.org/packages/LibUsbDotNet), to let you manage it from now on.

**Comment by qmfrederik** [comment]
Hi @GeorgeHahn !

We're bringing some new life in the LibUsbDotNet project (amongst other, .NET Core compatibility & reviewing the architecture).

Since you are the owner of the NuGet package for LibUsbDotNet and we're managing the code from here, would it be possible for you to add me as a maintainer to the NuGet package? You can use the quamotion handle on NuGet.

Thanks!

**Comment by GeorgeHahn** [comment]
Good to see this library getting some care! All the best!

**Comment by qmfrederik** [comment]
@GeorgeHahn Thanks!

**Comment by owenkimbrell** [comment]
Still cant get the package to work. Thoughts?

**Comment by qmfrederik** [comment]
@owenkimbrell Can you open a separate issue with any problem you have getting the package to work?
