### ISSUE TITLE
UsbContext Not Exposed

### ISSUE THREAD

**Issue by MelbourneDeveloper** [LibUsbDotNet/LibUsbDotNet#72]
I downloaded the NuGet. UsbContext is not exposed. the Read.Write sample uses this, so I expected to be able to see the class in the NuGet. Has this been refactored away or something? 

Version: 2.2.29

Windows 10

![image](https://user-images.githubusercontent.com/16697547/49693164-81cfba80-fbbf-11e8-9a58-67a2f2af67a8.png)

**Comment by MelbourneDeveloper** [comment]
It seems as though this is not necessary and the old sample is just a red herring.

**Comment by jaimestuardo** [comment]
Hello... how have you solved it? I am facing the same problem.

**Comment by ahmetgul93** [comment]
Hello, Could u please how u solve it ? I'm having the same error ?

**Comment by blue00** [comment]
You can use UsbDevice.OpenUsbDevice instead:
```
// Todo: Use correct USB vendor and product ID.
UsbDeviceFinder usbDeviceFinder = new UsbDeviceFinder(0x0AA2, 0xB01);

// Todo: Dispose usbDevice.
usbDevice = UsbDevice.OpenUsbDevice(usbDeviceFinder);
```

**Comment by mcuee** [comment]
Keep this open as a FAQ item.

**Comment by mcuee** [comment]
Close this but keep as FAQ.

**Comment by mcuee** [comment]
Please refer to #89.

**Comment by MelbourneDeveloper** [comment]
@mcuee thanks for looking into all these items. I'm not able to do any investigation at the moment, but when I get time I will do a round of work to try to get Device .Net working with the latest LibUsbDotNet version.

It seems you have been working on it, but the only things I will need a working NuGet package, and working samples with the latest code. If that's all here, I won't need to bother you again in future.

**Comment by mcuee** [comment]
You can try the latest nuget package which is 3.097 alpha now to see if it works for you or not.
https://www.nuget.org/packages/LibUsbDotNet/3.0.97-alpha

Frederik has quite some improvements recently so that I can run benchmarkcon (V2 branch only, not yet the V3 main branch). So I am happy to join the project to help on the testing and supporting side. I was also on the testing side last time when Travis Robinson started the project. Take note I am not the developer myself and I knew very little about dotnet, even though I know quite a bit about libusb as a non-developer admin of libusb project and libusb-win32/libusbk/pyusb project.

**Comment by mcuee** [comment]
If you find any issues, please help to raise the issues in github. Thanks.
